feat: added transaction.md but not complete
blockchaininnovation/lecture pull request #6
Opened 2024-02-18 14:45 UTC by Yuto2399

ほとんど完了しています。ここから、MTGにおいてフィードバックを受け、また他の作成者の内容を鑑み、今後一週間で成果物として提示できる状態まで、精度を上げ最終仕上げに入ります。

2024-02-21 14:45 UTC, Yuto2399 commented
予定していた内容を書き終えました.
レビュー待ちになります

2024-02-26 08:29 UTC, shibano2 requested changes
気づいたところをつらつらコメントしました．
細かい部分もありますが対応お願いします．

2024-02-26 08:29 UTC, shibano2 commented on P01_bitcoin/transaction.md
> +`注：以降「pop」「push」といった単語が出てくるが、それぞれ「１番最後に入れたものを取り出す」「スタックに要素を追加する」という意味である。`
スタックというデータのいれものに対して，「１番上のものを取り出す」「1番上に要素を追加する」

2024-02-26 08:29 UTC, shibano2 commented on P01_bitcoin/transaction.md
> +  - データ、オペコードはLIFO（後入れ先出し）でスタックされる
というか，スタックはLIFOのデータ構造を表現しているものなので

LIFO（後入れ先出し）で管理される

のが自然か．

2024-02-26 08:29 UTC, shibano2 commented on P01_bitcoin/transaction.md
> +  - 故にシンプル
シンプルかどうか意見が分かれると嫌なのでカット．（気にする人そんなにいない気もしますが・・・．

2024-02-26 08:29 UTC, shibano2 commented on P01_bitcoin/transaction.md
> +  - またチューリング不完全だと、ループ、再帰、自身で強制終了しない他のgoto変数をサポートしない
「またチューリング不完全だと、」→ カット．


チューリング不完全とはチューリング完全ではないということなので，チューリング完全とは何なのかを軽く説明してあげるといいかも．

2024-02-26 08:29 UTC, shibano2 commented on P01_bitcoin/transaction.md
> +  - これにより、どんなシステム上でも同じプロセスで実行できる
ステートレスとは，文字通りステートを持たないという意味です．
説明文章との不整合を感じる．

2024-02-26 08:29 UTC, shibano2 commented on P01_bitcoin/transaction.md
> +  ![Bitcoin scriptの処理プロセス](./img/process.png)
画像はオリジナルに．

2024-02-26 08:29 UTC, shibano2 commented on P01_bitcoin/transaction.md
> +  - これら以外にもあるので注意してほしい
これら以外にどんなものがあるのか，リンクを貼る．

2024-02-26 08:29 UTC, shibano2 commented on P01_bitcoin/transaction.md
> +  | OP_CHECKSIG| デジタル署名が公開鍵とマッチするかを確かめる |
MTGで話をしましたが，CHECKSIGではどんな署名が来ることが想定されているのか（というかECDSA署名のメッセージは何が求められているのか）を調べていただけると助かります．

2024-02-26 08:29 UTC, shibano2 commented on P01_bitcoin/transaction.md
> +  - 通常の送金時に使用する場合，送金先アドレスの公開鍵も必要になる
公開鍵そのものはアドレスから抽出できないので，通常の送金では使いにくい，とか追記してください．

2024-02-26 08:29 UTC, shibano2 commented on P01_bitcoin/transaction.md
> +    （「東京大学大学院工学系研究科技術経営戦略学専攻ブロックチェーンイノベーション寄付講座」より引用）
これは引用する必要がないのでカット．

2024-02-26 08:29 UTC, shibano2 commented on P01_bitcoin/transaction.md
> +    - 支払い前にスクリプトの共有が必要
スクリプトというか，受け取り側のいくつかの公開鍵．

2024-02-26 08:29 UTC, shibano2 commented on P01_bitcoin/transaction.md
> +  - 通常のBitcoin Scriptの実行手順と少し異なる
Redeemスクリプトの実行順について，資料中に，どっかのWebサイトの記事を参考にした記憶があるのでそこを引用してください．

2024-02-26 08:29 UTC, shibano2 commented on P01_bitcoin/transaction.md
> +  - *Version Prefixには「５」を使用し、アドレスは「３」から始まる
数値は半角で．

2024-02-26 08:29 UTC, shibano2 commented on P01_bitcoin/transaction.md
> +  - しかし後述するように、vinだけ少し特殊になっている
後述が多いなーと感じています．

「後述」とか記載する際は，どこに書いてあるのかページ内リンクを貼ってください．（他の箇所も同様）

2024-02-26 08:29 UTC, shibano2 commented on P01_bitcoin/transaction.md
> +    $vout = Sum(transactionFees) + halvingRelative$
左辺はvoutじゃなくて，voutの総額？
halvingRelativeとは？

2024-02-26 08:29 UTC, shibano2 commented on P01_bitcoin/transaction.md
> +  - 意味は不明（マイニング開始の日付を残すためだとか）
タイムズ紙のその日の見出しだったと思います．

2024-02-26 08:29 UTC, shibano2 commented on P01_bitcoin/transaction.md
> +- Coinbaseトランザクションは、少なくとも100回の確認を受ける（100ブロック後）まで使用できない
これ，私もよくわかってないところで，ソースを調べてリンク貼っておいてくれると助かります．

2024-02-26 08:29 UTC, shibano2 commented on P01_bitcoin/transaction.md
> +- **SegWit**とは、**署名データをトランザクションデータから分離したトランザクション方式のこと**
署名データはどこに置かれるのか，その署名はビットコインスクリプト的にどのように処理されるのかまで詳しく調べて記述をお願いします．

2024-03-02 06:22 UTC, imada-dchain commented on P01_bitcoin/transaction.md
> +  - ノードに関係のあるヘッダーしか取得しないため軽量である一方で、閲覧できる情報に制限がある
調べてみましたが、SPVの実装による部分があってもおかしくないので明確な言及を控えます。

2024-03-02 06:54 UTC, imada-dchain commented on P01_bitcoin/transaction.md
> +- PoWの目的は、ノード同士が相互に信頼できない環境（P2P）において、すべてのノード間で合意、つまり相互に信頼を得ることにある
うまくまとめられそうにないので、上記の内容を編集し追加しておきました。

2024-03-02 07:00 UTC, imada-dchain commented on P01_bitcoin/transaction.md
> +  - 現在の電力消費量は年間59TWを超えるといわれている
ありがとうございます。

2024-03-02 08:25 UTC, imada-dchain commented
まだ修正途中です。明日中にはすべての変更を終えます。

2024-03-03 08:18 UTC, imada-dchain commented on P01_bitcoin/transaction.md
> +  | 同時処理 | ○ | |
ビットコインが並列処理をサポートしているわけではない、という簡単な注を追加しました。

2024-03-03 08:39 UTC, imada-dchain commented on P01_bitcoin/transaction.md
> +  | 対リプレイアタック | ○ | |
厳密さに欠けるので削除します。

2024-03-03 08:39 UTC, imada-dchain commented on P01_bitcoin/transaction.md
> +  - また、UTXOはリプレイアタックのリスクが低い
表と同じく削除します

2024-03-03 08:52 UTC, imada-dchain commented on P01_bitcoin/transaction.md
> +- UTXOセットは新たなブロックが作成されるごとに更新されブロードキャストされる
おっしゃる通り、UTXOセット自体はブロードキャストされないです。私が言いたかったはずのことは、ブロードキャストされたトランザクションから、各ノードがUTXOセットを構築するということです。言葉が正確ではなかったです。申し訳ございません。

2024-03-03 09:01 UTC, imada-dchain commented on P01_bitcoin/transaction.md
> +- UTXOのデータ構造は、Bitcoinのパフォーマンスとストレージ要件に直接影響を及ぼす
DB実装についての話です。実質的にFull nodeが検証・マイニングを行うため、Full nodeの処理性能にかかわる部分がBitcoinのパフォーマンスにも影響を及ぼす、ということです。一応その旨の説明を追加しておきます。

2024-03-03 09:38 UTC, imada-dchain commented on P01_bitcoin/transaction.md
> +（「東京大学大学院工学系研究科技術経営戦略学専攻ブロックチェーンイノベーション寄付講座」より引用）
同じトランザクションIDが載っているだけなのですが、一応リンクを記載しておきます。

2024-03-06 01:08 UTC, imada-dchain commented on P01_bitcoin/transaction.md
> +    - *ロックを使用する場合、22番目のビットが１であれば、秒単位の使用を意味する
説明セクションを追加しました。

2024-03-06 01:09 UTC, imada-dchain commented on P01_bitcoin/transaction.md
> +    - *512秒なのはBitcoinのBlock timeが10分（600秒）に設定されているためである
そうBIPに明記してあるという記述と、それに関する簡潔な考察を追加しました。

2024-03-06 12:15 UTC, imada-dchain commented on P01_bitcoin/transaction.md
> +    - 例えば、アリスがボブにお金を支払う例。3か月後に有効になるロッキングスクリプトとなっている
vin , vout の説明を前に移動しました。

2024-03-06 12:27 UTC, imada-dchain commented on P01_bitcoin/transaction.md
> +      （「東京大学大学院工学系研究科技術経営戦略学専攻ブロックチェーンイノベーション寄付講座」より引用）
引用元が見つからなかったので、数値や人物を変更します

2024-03-06 12:49 UTC, imada-dchain commented on P01_bitcoin/transaction.md
> +- また手数料は指定することもできる
ウォレットなどでは自動で指定してくれるということを言いたかったです。誤解を生みそうなので訂正します。

2024-03-06 12:59 UTC, imada-dchain commented on P01_bitcoin/transaction.md
> +- ノードによっては、すでに送信したトランザクションの手数料をあとから変更することもできる
フラグを立てておくことで、ブロックに取り込まれるまでに手数料の変更をすることができるというだけであって、おっしゃる通りトランザクションの取り下げはできません。

2024-03-08 22:59 UTC, imada-dchain commented on P01_bitcoin/transaction.md
> +  | OP_CHECKSIG| デジタル署名が公開鍵とマッチするかを確かめる |
調べてみたのですが、すべてをうまく「トランザクション」の一環に組み込むのがとても難しいです。もし本当に入れるのであれば、説明する側としてはECDSAが何なのか、という内容がどこかで触れられていないとそこから説明しなくてはならず、これは脱線が過ぎる気がします。また、CHECKSIGの挙動はSegWitの有無、適応されるBIPによっても異なるみたいです。うまくまとめることができる気がしないので、今回はいったん「解決」としてマークしますが、Issue の方に挙げておこうと思います。

2024-03-09 00:14 UTC, imada-dchain commented
上記すべてを修正しました（ECDSAの件を除く）。
レビュー待ちになります。

2024-03-24 20:13 UTC, imada-dchain commented
コメントを付したので、TODOが大文字で残っているところだけでも先に目を通していただければと思います。

2024-03-26 17:57 UTC, imada-dchain commented
レビューをお願い致します。

2024-04-02 03:08 UTC, shibano2 approved these changes

2024-04-02 03:08 UTC, merged